# NumPy

NumPy (**Numerical Python**) is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures efficiently.

In [9]:
import numpy as np

### Features

1. **N-Dimensional Array Object (ndarray)**: The core of NumPy is the `ndarray`, a fast and space-efficient multidimensional array providing vectorized operations.
2. **Mathematical Functions** to perform operations on arrays.
3. Functions for **Linear Algebra** operations.
4. **Random Number Generation**
5. **Integration with Other Libraries**, such as SciPy, Pandas, and Matplotlib.


> NumPy operations are implemented in C, making them much faster than standard Python loops.

In [10]:
# Create a 1D array
a = np.array([1, 2, 3, 4, 5])
print("1D Array:", a)

# Create a 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", b)

# Perform basic operations
sum_array = np.sum(a)
print("Sum of array:", sum_array)
mean_array = np.mean(a)
print("Mean of array:", mean_array)

# Perform element-wise addition
c = a + 10
print("Element-wise addition:", c)

# Matrix multiplication
d = np.dot(b, b.T)
print("Matrix multiplication:\n", d)

# Broadcasting: Perform operations on two arrays with different shapes
e = b + a[:3]
print("Broadcasting:\n", e)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Sum of array: 15
Mean of array: 3.0
Element-wise addition: [11 12 13 14 15]
Matrix multiplication:
 [[14 32]
 [32 77]]
Broadcasting:
 [[2 4 6]
 [5 7 9]]


#### 1. Element-wise comparisons of two arrays.

In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([5, 1, 3])

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Greater:", np.greater(arr1, arr2))
print("Greater or equal:", np.greater_equal(arr1, arr2))
print("Equal:", np.equal(arr1, arr2))
print("Less:", np.less(arr1, arr2))
print("Less or equal:", np.less_equal(arr1, arr2))

Array 1: [1 2 3]
Array 2: [5 1 3]
Greater: [False  True False]
Greater or equal: [False  True  True]
Equal: [False False  True]
Less: [ True False False]
Less or equal: [ True False  True]


#### 2. An array of all the even integers from 30 to 70.

In [24]:
# arange(start, stop, step)
np.arange(30, 71, 2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

#### 3. 3x3 identity matrix.

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 4. Create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [36]:
vector = np.arange(21)
print("Original:", vector)

vector[(vector >= 9) & (vector <= 15)] *= -1
print("Modified:", vector)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Modified: [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


#### 5. Create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [40]:
np.diag(np.arange(1, 6))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 6.  Compute sum of all elements, sum of each column and sum of each row of a given array.

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Sum:", arr.sum())
print("Row sums:", arr.sum(axis=1))
print("Column sums:", arr.sum(axis=0))

Sum: 45
Row sums: [ 6 15 24]
Column sums: [12 15 18]


#### 7. Save a given array to a text file and load it.

In [47]:
np.savetxt("array.txt", arr)
np.loadtxt("array.txt")

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

#### 8. Check whether two arrays are equal (element wise) or not.

In [49]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.array_equal(arr1, arr2))
print(np.array_equal(arr1, arr1))

False
True


#### 9. Create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [56]:
arr = np.random.rand(4, 4)
print("Array:\n", arr)

arr[[0, 3]] = arr[[3, 0]]
print("Swapped:\n", arr)

Array:
 [[0.57260161 0.83476705 0.63451441 0.63715579]
 [0.8652799  0.74594091 0.61145695 0.36323134]
 [0.69354263 0.93268051 0.87538163 0.56886437]
 [0.94861205 0.99747614 0.78143581 0.77932476]]
Swapped:
 [[0.94861205 0.99747614 0.78143581 0.77932476]
 [0.8652799  0.74594091 0.61145695 0.36323134]
 [0.69354263 0.93268051 0.87538163 0.56886437]
 [0.57260161 0.83476705 0.63451441 0.63715579]]


#### 10. Multiply two given arrays of same size element-by-element

In [62]:
arr1, arr2 = np.arange(1, 6), np.arange(1, 10, 2)
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Product:", arr1 * arr2)

Array 1: [1 2 3 4 5]
Array 2: [1 3 5 7 9]
Product: [ 1  6 15 28 45]
