In [1]:
import numpy as np

In [5]:
a=np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Sum:", np.sum(arr))
print("Sum:", arr.sum())
print("Row sums:", arr.sum(1))
print("Column sums:", arr.sum(0))

Sum: 45
Sum: 45
Row sums: [ 6 15 24]
Column sums: [12 15 18]


In [11]:
np.savetxt("array.txt", arr)
np.loadtxt("array.txt")

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.equal(arr1, arr2))
print(np.equal(arr1, arr1))

[False False False]
[ True  True  True]


In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.array_equal(arr1, arr2))
print(np.array_equal(arr1, arr1))

False
True


In [18]:

arr1, arr2 = np.arange(1, 6), np.arange(1, 10, 2)
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Product:", arr1 * arr2)
x=np.dot(arr1,arr2)
print("array multiplication:",x)

Array 1: [1 2 3 4 5]
Array 2: [1 3 5 7 9]
Product: [ 1  6 15 28 45]
array multiplication: 95


In [19]:
import numpy  as np
m1=np.array([[1,2],[3,4]])
m2=np.array([[2,4],[6,8]])
print("Dot: \n",m1.dot(m2))
print("transpose: \n",np.transpose(m1))
print("transpose: \n",m1.T)
print("inverse\n",np.linalg.inv(m1))
print("determinant\n",np.linalg.det(m1))
print("1D array\n",m1.flatten())

Dot: 
 [[14 20]
 [30 44]]
transpose: 
 [[1 3]
 [2 4]]
transpose: 
 [[1 3]
 [2 4]]
inverse
 [[-2.   1. ]
 [ 1.5 -0.5]]
determinant
 -2.0000000000000004
1D array
 [1 2 3 4]


In [ ]:
a=[1,2,3]
print(np.array(a))